# Generated by Django 6.0.3 on 2026-03-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_viaje', models.CharField(max_length=100, unique=True, verbose_name='Número de viaje')),
                ('origen', models.CharField(max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('gastos_casetas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos de casetas')),
                ('gastos_diesel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gastos de diesel')),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otros gastos')),
                ('costo_viaje', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del viaje')),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
