# Generated by Django 6.0.3 on 2026-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ganancia'),
        ),
    ]
