# Generated by Django 6.0.3 on 2026-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0002_alter_viaje_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de viaje'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='numero_contenedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de contenedor'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de factura'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Viaje pagado?'),
        ),
    ]
