# Generated by Django 5.2.12 on 2026-05-06 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0005_cliente_operador_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='rendimiento_km_litro',
            field=models.DecimalField(decimal_places=2, default=3.5, help_text='Kilómetros por litro de diesel. Ej: 3.5 para camión sencillo cargado.', max_digits=5, verbose_name='Rendimiento (km/litro)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='km_distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distancia (km, solo ida)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio_diesel_litro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio diesel por litro ($)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trailers.unidad', verbose_name='Unidad (camión)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='viaje_redondo',
            field=models.BooleanField(default=False, verbose_name='¿Viaje redondo (ida y vuelta)?'),
        ),
    ]
