# Generated by Django 5.2.12 on 2026-05-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0006_unidad_rendimiento_km_litro_viaje_km_distancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de unidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('rendimiento_km_litro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento típico (km/litro)')),
            ],
            options={
                'verbose_name': 'Tipo de Unidad',
                'verbose_name_plural': 'Tipos de Unidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trailers.tipounidad', verbose_name='Tipo de unidad'),
        ),
    ]
