# Generated by Django 5.2.12 on 2026-05-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0008_seed_tipos_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='precio_diesel_litro',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Precio diesel por litro ($)'),
        ),
    ]
